# Generated by Django 5.2.5 on 2025-08-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True, verbose_name='Обозначение узла')),
                ('verbose_name', models.CharField(max_length=100, verbose_name='Название узла')),
            ],
            options={
                'indexes': [models.Index(fields=['verbose_name'], name='core_compon_verbose_78d412_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tractor_model', models.CharField(max_length=3, verbose_name='Модель трактора')),
                ('engine_comp', models.CharField(max_length=3, verbose_name='Производитель ДВС')),
                ('first_number', models.PositiveSmallIntegerField(verbose_name='Первые цифры в названии прошивки')),
                ('second_number', models.PositiveSmallIntegerField(verbose_name='Вторые цифры в названии прошивки')),
                ('third_number', models.PositiveSmallIntegerField(verbose_name='Третие цифры в названии прошивки')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Критическое обновление')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.component', verbose_name='Узел')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assamblies', to='core.component', verbose_name='Узел')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assamblies', to='core.softwareversion', verbose_name='Нынешняя версия прошивки')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID in Omnicomm')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('components', models.ManyToManyField(related_name='tractors', through='core.Assembly', through_fields=('tractor', 'component'), to='core.component', verbose_name='Компоненты')),
                ('software_versions', models.ManyToManyField(related_name='tractors', through='core.Assembly', through_fields=('tractor', 'software_version'), to='core.softwareversion', verbose_name='Версии прошивок')),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='tractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assamblies', to='core.tractor', verbose_name='Трактор'),
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(fields=('tractor_model', 'engine_comp', 'first_number', 'second_number', 'third_number'), name='unique_version'),
        ),
        migrations.AddIndex(
            model_name='tractor',
            index=models.Index(fields=['name'], name='core_tracto_name_2c8fc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(fields=('tractor', 'component', 'software_version'), name='unique_assembly'),
        ),
    ]
