# Generated by Django 5.2.5 on 2025-08-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractor',
            name='components',
        ),
        migrations.RemoveField(
            model_name='tractor',
            name='software_versions',
        ),
        migrations.AlterField(
            model_name='component',
            name='verbose_name',
            field=models.CharField(choices=[('EN', 'ДВС'), ('TB', 'Коробка передач'), ('SC', 'Рулевая колонка'), ('HD', 'Гидрораспределитель'), ('DP', 'Дисплей'), ('CN', 'Контроллер')], max_length=2, verbose_name='Название узла'),
        ),
    ]
