# Generated by Django 5.2.5 on 2025-08-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tractor_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='components',
            field=models.ManyToManyField(related_name='tractors', through='core.Assembly', through_fields=('tractor', 'component'), to='core.component', verbose_name='Компоненты'),
        ),
        migrations.AddField(
            model_name='tractor',
            name='software_versions',
            field=models.ManyToManyField(related_name='tractors', through='core.Assembly', through_fields=('tractor', 'software_version'), to='core.softwareversion', verbose_name='Версии прошивок'),
        ),
    ]
