# Generated by Django 5.2.5 on 2025-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tractor_components_tractor_software_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='is_broken',
            field=models.BooleanField(default=False, verbose_name='Неисправная версия'),
        ),
    ]
