# Generated by Django 5.2.5 on 2025-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_softwareversion_is_broken'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Старое обозначение ПО'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='engine_comp',
            field=models.CharField(blank=True, max_length=3, verbose_name='Производитель ДВС'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='first_number',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Первые цифры в названии прошивки'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='second_number',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Вторые цифры в названии прошивки'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='third_number',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Третие цифры в названии прошивки'),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='tractor_model',
            field=models.CharField(blank=True, max_length=3, verbose_name='Модель трактора'),
        ),
    ]
