# Generated by Django 5.2.5 on 2025-08-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_softwareversion_engine_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обозначение ПО'),
        ),
    ]
