# Generated by Django 5.2.5 on 2025-08-25 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_softwareversion_engine_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата выпуска'),
        ),
    ]
