# Generated by Django 5.2.5 on 2025-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_softwareversion_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='verbose_name',
            field=models.CharField(choices=[('EN', 'ДВС'), ('TB', 'Коробка передач'), ('SC', 'Рулевая колонка'), ('HD', 'Гидрораспределитель'), ('DP', 'Дисплей'), ('CN', 'Контроллер')], max_length=2, verbose_name='Узел'),
        ),
    ]
