# Generated by Django 5.2.5 on 2025-08-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_component_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
    ]
