# Generated by Django 5.2.5 on 2025-08-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_softwareversion_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwareversion',
            options={'ordering': ['-release_date', '-version']},
        ),
    ]
